version: '3'

services:
  db_flask:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - production-network

  web_api_flask:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db_flask
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
